version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - for-fastapi
    depends_on:
      - fast-api-server

  fast-api-server:
    image: fastapi-hello-world:latest
    build: .
    container_name: fast-api-server
    environment:
      - REDIS_URL=redis://my-redis:6379
    ports:
      - "8000:8000"
    networks:
      - for-fastapi
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: my-redis
    networks:
      - for-fastapi
    ports:
      - "6379:6379"

networks:
  for-fastapi: