version: '3'

networks:
  for-fastapi:

services:
  fast-api-server:
    image: fastapi-docker-image:latest
    build:
      context: ..
      dockerfile: devops/Dockerfile
    container_name: fast-api-server
    environment:
      - REDIS_URL=redis://redis-for-fastapi:6379
    ports:
      - "8000:8000"
    networks:
      - for-fastapi
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-for-fastapi
    networks:
      - for-fastapi
    ports:
      - "6379:6379"


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - for-fastapi
    depends_on:
      - fast-api-server
