apiVersion: v1
kind: Service
metadata:
  name: fast-api-server-service
spec:
  selector:
    app: fast-api-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
